defaults: &defaults
  working_directory: ~/imdb-rater
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/imdb-rater
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  dependencies-and-test:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies